---

 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (CentOS)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution in ["Ubuntu","Debian"]

 - hosts: workstations
   become: true
   tasks:

   - name: install unzip
     package:
       name: unzip

   - name: install terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root


 - hosts: web_servers
   become: true
   tasks:

   - name: install httpd package (CentOS)
     tags: apache,centos,httpd
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"

   - name: install apache2 package (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution in ["Ubuntu","Debian"]

   - name: copy html file for site
     tags: apache,apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644



 - hosts: db_servers
   become: true
   tasks:

   - name: install mariadb server package (CentOS)
     tags: centos,db,postgresql
     dnf:
       name: postgresql
       state: latest
     when: ansible_distribution == "CentOS"

   - name: install postgresql server
     tags: db,postgresql,ubuntu
     apt:
       name: postgresql
       state: latest
     when: ansible_distribution in ["Ubuntu","Debian"]

 - hosts: file_servers
   tags: samba
   become: true
   tasks:

   - name: install samba package
     tags: samba
     package:
       name: samba
       state: latest
